services:
  postgres:
    image: postgres:16-alpine
    platform: linux/amd64
    container_name: postgres_barberia
    restart: unless-stopped
    environment:
      POSTGRES_DB: barberia_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: America/El_Salvador
    ports:
      - "5432:5432"
    volumes:
      - postgres_barberia:/var/lib/postgresql/data

volumes:
  postgres_barberia:
